doctrine_migrations:
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: migration_versions
    enable_profiler: '%kernel.debug%'
