simple_things_entity_audit:
    audited_entities:
        - App\Entity\Company
        - App\Entity\Person
        - App\Entity\Role
        - App\Entity\Workcenter
        - App\Entity\Edu\AcademicYear
        - App\Entity\Edu\ContactMethod
        - App\Entity\Edu\PerformanceScale
        - App\Entity\Edu\PerformanceScaleValue
        - App\Entity\ItpModule\Activity
        - App\Entity\ItpModule\CompanyProgram
        - App\Entity\ItpModule\ProgramGrade
        - App\Entity\ItpModule\ProgramGradeLearningOutcome
        - App\Entity\ItpModule\SpecificTraining
        - App\Entity\ItpModule\StudentLearningProgram
        - App\Entity\ItpModule\StudentLearningProgramActivity
        - App\Entity\ItpModule\StudentLearningProgramActivityComment
        - App\Entity\ItpModule\TrainingProgram
        - App\Entity\ItpModule\TrainingProgramGroup
        - App\Entity\ItpModule\WorkDay
        - App\Entity\WltModule\AgreementActivityRealization
        - App\Entity\WltModule\AgreementActivityRealizationComment
        - App\Entity\WltModule\Contact
        - App\Entity\WltModule\EducationalTutorAnsweredSurvey
        - App\Entity\WltModule\LearningProgram
        - App\Entity\WltModule\Meeting
        - App\Entity\WltModule\Project
        - App\Entity\WltModule\StudentAnsweredSurvey
        - App\Entity\WltModule\TravelExpense
        - App\Entity\WltModule\WorkDay
        - App\Entity\WltModule\WorkTutorAnsweredSurvey
        - App\Entity\WptModule\Activity
        - App\Entity\WptModule\Agreement
        - App\Entity\WptModule\Contact
        - App\Entity\WptModule\EducationalTutorAnsweredSurvey
        - App\Entity\WptModule\Shift
        - App\Entity\WptModule\StudentAnsweredSurvey
        - App\Entity\WptModule\TravelExpense
        - App\Entity\WptModule\WorkDay
        - App\Entity\WptModule\WorkTutorAnsweredSurvey
        - App\Entity\Survey
        - App\Entity\SurveyQuestion
        - App\Entity\AnsweredSurvey
        - App\Entity\AnsweredSurveyQuestion
    global_ignore_columns:
        - last_access
