twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
    globals:
        app_name:     '%env(APP_NAME)%'
        app_repository: 'https://github.com/iesoretania/atica-fp'
        app_version:  '%app.version%'
        app_pub_date:  '%app.pub_date%'
        user_extension: '@App\Service\UserExtensionService'
        module_extension: '@App\Service\Module\ModuleService'
        organization_extension: '@App\Service\Organization\OrganizationBuilderChain'

when@test:
    twig:
        strict_variables: true
