version: '2'
services:
    db:
        image: mysql:8.4
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: aticafp
            MYSQL_USER: atica
            MYSQL_PASSWORD: atica
        volumes:
            - ./data:/var/lib/mysql
        restart: always

    app:
        image: iesoretania/atica-fp-app:7.0.0
        build: .
        environment:
            - "DEMO=${DEMO}"
        ports:
           - 9999:80
        restart: always
        depends_on:
           - db
