imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: '%session_name%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        app_name:     '%app_name%'
        app_repository: 'https://github.com/iesoretania/atica-fp'
        app_version:  'dual'
        user_extension: '@AppBundle\Service\UserExtensionService'
        menu_extension: "@app.menu_builders_chain"

# Doctrine Configuration
doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: '%database_charset%'
        default_table_options:
            charset: '%database_charset%'
            collate: '%database_collate%'
        types:
            datetime:
                class: AppBundle\DoctrineExtension\DBAL\Type\UTCDateTimeType
                commented: false
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.project_dir%/src/AppBundle/Migrations"
    namespace: AppBundle\Migrations
    table_name: migration_versions
    name: Application Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"

simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\Company
        - AppBundle\Entity\Person
        - AppBundle\Entity\Role
        - AppBundle\Entity\User
        - AppBundle\Entity\Workcenter
        - AppBundle\Entity\Edu\AcademicYear
        - AppBundle\Entity\WLT\AgreementActivityRealization
        - AppBundle\Entity\WLT\LearningProgram
        - AppBundle\Entity\WLT\Meeting
        - AppBundle\Entity\WLT\Visit
        - AppBundle\Entity\WLT\WorkDay
        - AppBundle\Entity\Survey
        - AppBundle\Entity\SurveyQuestion
        - AppBundle\Entity\AnsweredSurvey
        - AppBundle\Entity\AnsweredSurveyQuestion
    global_ignore_columns:
        - last_access
