# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role-hierarchy:
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(entrar|restablecer|publico)
            anonymous: ~
            logout_on_user_change: true

        main:
            logout_on_user_change: true

            guard:
                authenticators:
                - AppBundle\Security\FormAuthenticator

            logout:
                path: logout
                target: /

            switch_user:
                role: ROLE_ALLOWED_TO_SWITCH
                parameter: _switch_user

