controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#simple_things_entity_audit:
#    resource: "@SimpleThingsEntityAuditBundle/Resources/config/routing/audit.xml"
#    prefix: /audit
